- name: Andy Baxter
  github: andrewbaxter439
  langs: R, Python, Java, Javascript
- name: Ric Colasanti
  github: ric-colasanti
  langs: Python, Go, JavaScript
- name: Dylan Lewis
  github: dylan-w-lewis
  langs: R, Python
